
export var RouteAPI = {
  routes: [
    {
      depCode: "EVN",
      depAirportName: "Yerevan",
      countryCode: "AM",
      countryName: "Armenia",
      isNew: false,
      arrCodes: [
        "BRU",
        //"BOJ",
        "LCA",
        "PRG",
        "HRG",
        "RMF",
        "SSH",
        "CDG",
        "LYS",
        "NCE",
        "TBS",
        "BER",
        "DUS",
        "HHN",
        "MUC",
        "IKA",
        "DUB",
        "TLV",
        "BLQ",
        "MXP",
        "PMF",
        "FCO",
        "VCE",
        "VRN",
        "BEY",
        "TIV",
        "KIV",
        "AMS",
        "LIS",
        "SVX",
        "KRR",
        "MRV",
        "MOW",
        "VKO",
        "DME",
        "OVB",
        "KUF",
        "LED",
        "AER",
        "BCN",
        "MAD",
        "VLC",
        "ZRH",
        "IST",
        //	   'KBP',
        "DWC",
        "LHR",
        "LTN",
      ],
    },

    {
      depCode: "BRU",
      depAirportName: "Brussels",
      countryCode: "BE",
      countryName: "Belgium",
      isNew: false,
      arrCodes: [
        "EVN",
        "GYD",
        "BUS",
        "TBS",
        "IKA",
        "TLV",
        "BEY",
        "KIV",
        "SVX",
        "KRR",
        "MRV",
        "MOW",
        "VKO",
        "DME",
        "OVB",
        "KUF",
        "AER",
        "LED",
        "IST",
        "DWC",
        //			"BUS",
        //			"KBP",
      ],
    },
    {
      depCode: "BOJ",
      depAirportName: "Burgas",
      countryCode: "BG",
      countryName: "Bulgaria",
      isNew: true,
      arrCodes: [
        "EVN",
        "TBS",
        "SVX",
        "KRR",
        "MRV",
        "MOW",
        "VKO",
        "DME",
        "OVB",
        "KUF",
        "LED",
        "AER",
      ],
    },
    {
      depCode: "LCA",
      depAirportName: "Larnaca",
      countryCode: "CY",
      countryName: "Cyprus",
      isNew: true,
      arrCodes: [
        "EVN",
        "TBS",
        "BRU",
        "PRG",
        "CDG",
        "LYS",
        "NCE",
        "BER",
        "DUS",
        "HHN",
        "MUC",
        "DUB",
        "BLQ",
        "MXP",
        "PMF",
        "FCO",
        "VRN",
        "VCE",
        "KIV",
        "AMS",
        "LIS",
        "SVX",
        "KRR",
        "MRV",
        "MOW",
        "VKO",
        "DME",
        "OVB",
        "KUF",
        "LED",
        "AER",
        "BCN",
        "MAD",
        //			 'VLC',
        //			 'DWC',
        "LTN",
        "LHR",
      ],
    },
  ],

  result: {
    isSuccess: true,
    msgs: null,
  },
};